version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: infra/docker/web.Dockerfile
    image: powerbase-web:dev
    container_name: powerbase-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    image: powerbase-api:dev
    container_name: powerbase-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./apps/api:/app
    depends_on:
      - db
      - redis
      - minio

  worker:
    build:
      context: .
      dockerfile: infra/docker/worker.Dockerfile
    image: powerbase-worker:dev
    container_name: powerbase-worker
    env_file:
      - .env
    volumes:
      - ./apps/worker:/app
    depends_on:
      - redis

  db:
    image: postgres:16-alpine
    container_name: powerbase-db
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: powerbase-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: powerbase-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

# No external networks necessary for dev