"""floorplans table

Revision ID: 06567529d71c
Revises: f11abc7079a3
Create Date: 2025-10-06 12:28:13.555657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06567529d71c'
down_revision: Union[str, Sequence[str], None] = 'f11abc7079a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floorplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='floorplanstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scene_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floorplans_facility_id'), 'floorplans', ['facility_id'], unique=False)
    op.create_index(op.f('ix_floorplans_status'), 'floorplans', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floorplans_status'), table_name='floorplans')
    op.drop_index(op.f('ix_floorplans_facility_id'), table_name='floorplans')
    op.drop_table('floorplans')
    # ### end Alembic commands ###