"""rbac tables

Revision ID: ba0d5e7d9673
Revises: 67b0cf70d5d9
Create Date: 2025-10-06 10:30:03.097743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0d5e7d9673'
down_revision: Union[str, Sequence[str], None] = '67b0cf70d5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: unique constraint 'uq_user_role' is created in the previous revision
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op: nothing to drop since this revision didn't create anything
    # ### end Alembic commands ###
